import js from '@eslint/js';
import { FlatCompat } from '@eslint/eslintrc';
import tsParser from '@typescript-eslint/parser';
import tsPlugin from '@typescript-eslint/eslint-plugin';
import reactPlugin from 'eslint-plugin-react';
import reactHooksPlugin from 'eslint-plugin-react-hooks';
import jsxA11yPlugin from 'eslint-plugin-jsx-a11y';
import importPlugin from 'eslint-plugin-import';

// airbnb, airbnb/hooks and the `plugin:`-style configs below ship eslintrc format only, so they
// come in through FlatCompat rather than being rewritten by hand — that keeps the resolved rule
// set byte-identical to the old .eslintrc.cjs.
const compat = new FlatCompat({
  baseDirectory: import.meta.dirname,
  recommendedConfig: js.configs.recommended,
  allConfig: js.configs.all,
});

// The old `lint` script passed `--ext .js,.jsx,.ts,.tsx`. Flat config would otherwise also pick
// up `.cjs` (server/index.cjs, the config files), so the scope is pinned here instead.
const FILES = ['**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx'];

export default [
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      // eslintrc skipped dot-directories by default; flat config does not, and .netlify holds
      // generated dev bundles.
      '.netlify/**',
      'src/api/generated/**',
      'src/libs/__tests__/**',
      'src/api/solana-program/generated/**',
      // Generated by `npm run generate:solana-program-client` (not hand-maintained)
      'src/api/solana-program/**',
    ],
  },

  ...compat.extends(
    'airbnb',
    'airbnb/hooks',
    'plugin:@typescript-eslint/recommended',
    'plugin:import/typescript',
  ).map((config) => ({ ...config, files: FILES })),

  ...compat.env({ browser: true, es2021: true, node: true }).map((config) => ({
    ...config,
    files: FILES,
  })),

  {
    files: FILES,
    languageOptions: {
      parser: tsParser,
      ecmaVersion: 2021,
      sourceType: 'module',
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
    },
    settings: {
      react: {
        version: 'detect',
      },
      'import/resolver': {
        typescript: {
          project: './tsconfig.json',
        },
        node: {
          extensions: ['.js', '.jsx', '.ts', '.tsx'],
        },
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
      react: reactPlugin,
      'react-hooks': reactHooksPlugin,
      'jsx-a11y': jsxA11yPlugin,
      import: importPlugin,
    },
    rules: {
      // Imports & module resolution
      'import/extensions': [
        'error',
        'ignorePackages',
        {
          pattern: {
            js: 'never',
            jsx: 'never',
            ts: 'never',
            tsx: 'never',
          },
          // @noble/* and @scure/* v2 expose `.js`-suffixed subpaths only, so the extension is
          // required by their exports maps rather than being a style choice.
          pathGroupOverrides: [
            { pattern: '@noble/**', action: 'ignore' },
            { pattern: '@scure/**', action: 'ignore' },
          ],
        },
      ],
      'import/prefer-default-export': 'off',
      'import/no-extraneous-dependencies': ['error', {
        devDependencies: [
          '**/*.test.{ts,tsx}',
          '**/*.spec.{ts,tsx}',
          'vitest.setup.ts',
          'vite.config.ts',
          'eslint.config.js',
          'playwright*.config.ts',
          'tsconfig*.json',
          'scripts/**',
        ],
      }],

      // General JS / TS
      'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
      'linebreak-style': 'off', // allow Windows-style line endings in repo

      // TypeScript-specific relaxations
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/no-empty-object-type': 'off',

      // React
      'react/react-in-jsx-scope': 'off', // React 17+ / Vite
      'react/jsx-filename-extension': ['warn', { extensions: ['.tsx'] }],
      'react/jsx-props-no-spreading': 'off',
      'react/require-default-props': 'off',
      'react/prop-types': 'off',
      'react/jsx-no-bind': 'off',
      'react/function-component-definition': [2, {
        namedComponents: 'arrow-function',
        unnamedComponents: 'arrow-function',
      }],
      'jsx-a11y/control-has-associated-label': 'warn',
      'jsx-a11y/label-has-associated-control': 'warn',

      // Developer-experience tweaks
      'max-len': ['warn', {
        code: 100,
        ignoreUrls: true,
        ignoreStrings: true,
        ignoreTemplateLiterals: true,
      }],
      'no-console': 'warn',
      'no-alert': 'warn',
    },
  },

  ...compat.env({ jest: true }).map((config) => ({
    ...config,
    files: ['**/*.test.{ts,tsx}', '**/*.spec.{ts,tsx}'],
  })),
  {
    files: ['**/*.test.{ts,tsx}', '**/*.spec.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },

  {
    files: ['docker/init-state.ts'],
    rules: {
      'no-console': 'off',
    },
  },
];
