site_name: Superhero Hackathon
repo_url: https://github.com/superhero-com/superhero
repo_name: superhero-com/superhero
use_directory_urls: true

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.tabs.link
    - toc.follow

nav:
  - Home: index.md
  - Quickstart: tutorials/hackathon/00a-quickstart.md
  - Setup: tutorials/hackathon/02-setup.md
  - Build:
      - Scaffold & Compiler (aeproject): tutorials/hackathon/03-scaffold-and-compiler.md
      - Contracts: tutorials/hackathon/04-contracts.md
      - Test & Deploy (aeproject): tutorials/hackathon/05-test-and-deploy.md
      - Integrate & Plugin SDK: tutorials/hackathon/06-integrate-and-plugin-sdk.md
  - Operations: tutorials/hackathon/08-ops-and-support.md

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
